### ISSUE TITLE
ClassNotFoundException / NoClassDefFoundError when trying to use libgphoto2-jna

### ISSUE THREAD

**Issue by mxjones** [angryelectron/libgphoto2-jna#8]
Hi,

I am inexperienced in Java programming so this may be unrelated to this library.

I have created a simple test application in NetBeans IDE using sample code from ReadMe.

```
GPhoto2 camera = new GPhoto2();
camera.open();
camera.capture();
camera.close()
```

When the test app is run it throws an exception whilst creating an instance of GPhoto2:
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/jna/Callback
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at testapp.TestApp.main(TestApp.java:21)
Caused by: java.lang.ClassNotFoundException: com.sun.jna.Callback
    at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 13 more
Java Result: 1

I have downloaded the libgphoto2-jna source and built it, placing the .jar found in the dist folder within the directory of my test application and set it as a library so it is included in the class path.

Is this an issue with how I've set up my application?

Cheers

**Comment by mxjones** [comment]
Ok, after a few hours of getting no where I posted this and in the last 5 minutes I have got past this error. 

I just needed to add jna (https://github.com/twall/jna) jar file to my projects library.

Cheers
