### ISSUE TITLE
GPhoto2 captureTethered fails with code-107

### ISSUE THREAD

**Issue by mxjones** [angryelectron/libgphoto2-jna#9]
Hi,

I am using the captureTethered method to retrieve Images manually captured by the connected Camera, however it always fails with code -107 (Directory not found).

Debugging through the source code I can see that the CameraFilePath passed into saveImage always provides the folder and name as an empty string ("") so the gp_camera_file_get call fails.

SEVERE: Exception caught in Tether loop
java.io.IOException: gp_camera_file_get failed with code -107
    at com.angryelectron.gphoto2.GPhoto2.saveImage(GPhoto2.java:456)
    at com.angryelectron.gphoto2.GPhoto2.captureTethered(GPhoto2.java:331)
    at pidslrserver.CapturedImageManagerTetheredCapture$1.run(CapturedImageManagerTetheredCapture.java:72)
    at java.lang.Thread.run(Thread.java:745)

When using the gphoto2 in the command line --wait-event-and-download correctly downloads and saves the Image.

Is this a known issue with the tethering functionality?

Cheers

**Comment by mxjones** [comment]
Hi (again),

I have managed to get the filename & path from the captureTethered method with a couple small changes. I'm not sure if this already works for anyone else or if it is something in my set up that causes this method to not work for me so I won't issue a pull request unless requested.

Cheers
